### ISSUE TITLE
Invalid variable reference syntax for variable git:branch

### ISSUE THREAD

**Issue by hotgazpacho** [jacob-meacham/serverless-plugin-git-variables#13]
This plugin seems incompatible with the [`serverless-mocha-plugin`](https://github.com/nordcloud/serverless-mocha-plugin). Running `sls invoke test` with the git-variables plugin results in the following error:

`ServerlessError: Invalid variable reference syntax for variable git:branch. You can only reference env vars, options, & files. You can check our docs for more info.`

My custom section includes this:
```yaml
custom:
  git: ${git:branch} - ${git:describe} - ${git:sha1}
```

And my functions reference it like so:
```yaml
functions:
  graphql:
    name: ${self:provider.stage}-graphql
    description: GraphQL Handler (GET/POST /graphql) - ${self:custom.git}
    handler: functions/graphql.handler
```

Deploying works just fine. This only fails when trying to run my test suite.
